/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.Account;
import model.JDBC;
import model.Transaction;

/**
 *
 * @author Acer
 */
public class ATM extends javax.swing.JFrame {
    
    JDBC jdbc = null;
    
    private Account activeAccount = CustomerScreen.getActiveAccount();

    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
        
        btn200.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(false);
            }
            
        });
        
        btn100.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(false);
            }
            
        });
        
        btn50.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(false);
            }
            
        });
        
        btn20.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(false);
            }
            
        });
        
        btn10.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(false);
            }
            
        });
        
        
        btnOtherAmnt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawalField.setEditable(true);
            }
            
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        printStatementBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        depositField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        depositBtn = new javax.swing.JButton();
        withdrawalField = new javax.swing.JTextField();
        withdrawalBtn = new javax.swing.JButton();
        btn200 = new javax.swing.JRadioButton();
        btn100 = new javax.swing.JRadioButton();
        btn50 = new javax.swing.JRadioButton();
        btn20 = new javax.swing.JRadioButton();
        btn10 = new javax.swing.JRadioButton();
        depositAlert = new javax.swing.JLabel();
        withdrawAlert = new javax.swing.JLabel();
        btnOtherAmnt = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        jLabel2.setText("Withdrawals:");

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 21)); // NOI18N
        jLabel4.setText("Deposits:");

        printStatementBtn.setText("PRINT STATEMENT");
        printStatementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printStatementBtnActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        depositField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount (BWP):");

        depositBtn.setText("Deposit");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        withdrawalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalFieldActionPerformed(evt);
            }
        });

        withdrawalBtn.setText("Withdraw");
        withdrawalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn200);
        btn200.setSelected(true);
        btn200.setText("P 200");

        buttonGroup1.add(btn100);
        btn100.setText("P 100");

        buttonGroup1.add(btn50);
        btn50.setText("P50");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn20);
        btn20.setText("P 20");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn10);
        btn10.setText("P 10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        depositAlert.setForeground(new java.awt.Color(204, 0, 0));

        withdrawAlert.setForeground(new java.awt.Color(204, 0, 0));

        buttonGroup1.add(btnOtherAmnt);
        btnOtherAmnt.setText("Own Amount");
        btnOtherAmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherAmntActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel3.setText("PULA BANKING ATM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(printStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn200)
                                    .addComponent(btnOtherAmnt)
                                    .addComponent(btn100))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn20)
                                    .addComponent(btn10)
                                    .addComponent(btn50)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(withdrawalField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(withdrawalBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawAlert)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositBtn))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositAlert)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(withdrawAlert)
                            .addComponent(depositAlert))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn200)
                            .addComponent(btn50))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn100)
                            .addComponent(btn20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn10)
                            .addComponent(btnOtherAmnt)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withdrawalField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalBtn)
                            .addComponent(depositBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printStatementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printStatementBtnActionPerformed
        BankStatement bs = new BankStatement();
        bs.setVisible(true);
    }//GEN-LAST:event_printStatementBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Take to Customer Screen            
        CustomerScreen cs = new CustomerScreen();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void depositFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositFieldActionPerformed

    private void withdrawalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawalFieldActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void withdrawalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalBtnActionPerformed
        
        String withdrawal = "";
        double withdrawalAmount = 0;
        
        btn200.setActionCommand("200");
        btn100.setActionCommand("100");
        btn50.setActionCommand("50");
        btn20.setActionCommand("20");
        btn10.setActionCommand("10");
        btnOtherAmnt.setActionCommand(withdrawalField.getText());
        
        if(withdrawalField.getText().equals("")) {
            
            withdrawal = buttonGroup1.getSelection().getActionCommand();
        
        }else {
        
            withdrawal = withdrawalField.getText();
        
        }
        
        
        
        if(withdrawal.equals("")) {
            
            withdrawAlert.setText("Enter Amount !");
        
        }else {
        
            withdrawalAmount = Double.parseDouble(withdrawal);
            
        }
        
        if(!withdrawal.equals("")) {
            
            jdbc = new JDBC();
            
            double balance = jdbc.getAccountBalance(activeAccount.getAccNumber());
            
            // Check if funds are sufficient:
            if(withdrawalAmount > balance) {
                JOptionPane.showMessageDialog(null, "Account Balance Insufficient ! Current Balance: " + balance );
                withdrawalField.setText("");

            }else {
            
                jdbc = null;
            
                jdbc = new JDBC();

                jdbc.withdrawMoney(withdrawalAmount, activeAccount.getAccNumber(), balance);

                jdbc = null;

                jdbc = new JDBC();

                //Timestamp transactionDate, int accountId, double amount, String transactionType
                long time = System.currentTimeMillis();
                java.sql.Timestamp transactionDate = new java.sql.Timestamp(time);
                Transaction tr = new Transaction(transactionDate, activeAccount.getAccNumber(), withdrawalAmount, "Withdrawal");

                int success = jdbc.addTransaction(tr);

                if(success > 0) {
                    JOptionPane.showMessageDialog(null, "Withdrawal Successfull ! New Balance: " + (balance - withdrawalAmount));
                    withdrawalField.setText("");
                }
                
            }
            
            
            
        }
    }//GEN-LAST:event_withdrawalBtnActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50ActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        
        double depositAmount = 0;
        
        if(depositField.getText().equals("")) {
            
            depositAlert.setText("Please Enter Amount !");
        
        }else {
        
            depositAmount = Double.parseDouble(depositField.getText());
            
        
        }
        
        
        if(!depositField.getText().equals("")) {
            
            jdbc = new JDBC();
            
            double balance = jdbc.getAccountBalance(activeAccount.getAccNumber());
            
            jdbc = null;
            
            jdbc = new JDBC();
            
            jdbc.depositMoney(depositAmount, activeAccount.getAccNumber(), balance);
            
            jdbc = null;
            
            jdbc = new JDBC();
            
            //Timestamp transactionDate, int accountId, double amount, String transactionType
            long time = System.currentTimeMillis();
            java.sql.Timestamp transactionDate = new java.sql.Timestamp(time);
            Transaction tr = new Transaction(transactionDate, activeAccount.getAccNumber(), depositAmount, "Deposit");
            
            int success = jdbc.addTransaction(tr);
            
            if(success > 0) {
                JOptionPane.showMessageDialog(null, "Deposit Successfull ! New Balance: " + (balance + depositAmount));
                depositField.setText("");
            }
                
        }
    }//GEN-LAST:event_depositBtnActionPerformed

    private void btnOtherAmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherAmntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtherAmntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn10;
    private javax.swing.JRadioButton btn100;
    private javax.swing.JRadioButton btn20;
    private javax.swing.JRadioButton btn200;
    private javax.swing.JRadioButton btn50;
    private javax.swing.JRadioButton btnOtherAmnt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel depositAlert;
    private javax.swing.JButton depositBtn;
    private javax.swing.JTextField depositField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton printStatementBtn;
    private javax.swing.JLabel withdrawAlert;
    private javax.swing.JButton withdrawalBtn;
    private javax.swing.JTextField withdrawalField;
    // End of variables declaration//GEN-END:variables
}
